"""empty message

Revision ID: 591cf8d8a7b7
Revises: 5f5b2aa70d70
Create Date: 2022-05-06 13:43:33.207818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591cf8d8a7b7'
down_revision = '5f5b2aa70d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('icon', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'icon')
    # ### end Alembic commands ###
